<a href="https://colab.research.google.com/github/Nikhil09052007/Concepts_for_ML/blob/main/CAMPUSX_NUMPY_DSMP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

It is quite procastinating while revisiting the concepts again.

In [ ]:
import numpy as np


In [ ]:
# 1D array usnig a list in numpy

list_0 = [2,3,45,5]
np.array(list_0)

array([ 2,  3, 45,  5])

In [ ]:
#2d Array

b = np.array([[[1,2],[3,4],[5,6]]])

In [ ]:
b

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
# dtype stands for datatype in the array
# By default float is actually fixed in data type.
b = np.array(list_0,dtype=bool)

In [ ]:
# np.arange It works similar to range function
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape

np.arange(1,10).reshape(3,3) # It helps to matrix of the data.


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# np.ones and np.zeroes gives matrix of order
c = np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.random
d = np.random.random((2,3)) # works onn oop random class then method
d


array([[0.60481973, 0.61819959, 0.61253914],
       [0.80672417, 0.05509485, 0.70717665]])

In [ ]:
# np.linspace generates liniearly space points in a given space.

e = np.linspace(-10,10,10)
e

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.indentity creates identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Attributes**

In [ ]:
# ndim

# this means number of dimensions

b.ndim

1

In [ ]:
# shape
# shape tells the order of arary as matrx (row , columns)

c.shape

(2, 3)

In [ ]:
# size tells the number of object

c.size

6

In [ ]:
# itemize tells the type of data in the items taking the byte of storate

# int32 takes 4 bytes and 64 takes 8 bytes

b.itemsize

1

**Changing data types**


In [ ]:
#astype: we can trannsform the data type from int64 to int32 or float to int

b.astype(str)

b.astype(np.int32)

array([1, 1, 1, 1], dtype=int32)

**ARRAY OPERATIONS**
It helps to perform various and emmense amout of mathematical formulation and things.


In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar opeartions
a1 * 2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#arithmatic
a1 ** 3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [ ]:
# relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 >45

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
## Vector opeartions: when happens between two vectors
a1 + a2  #since size is same

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

**Array Functions**

In [ ]:
a1 = np.random.random((4,4))
a1 = np.round(a1*100) #
a1

array([[44., 14., 81., 98.],
       [74., 79., 77., 81.],
       [85., 82., 54., 39.],
       [53., 34., 14., 36.]])

In [ ]:
# max/min/sum/prod

np.max(a1)

np.float64(98.0)

In [ ]:
np.sum(a1)

np.float64(945.0)

In [ ]:
np.prod(a1)

np.float64(2.3768557740644187e+27)

In [ ]:
np.sum(a1)

np.float64(945.0)

In [ ]:
# max of a single row
# 0 means column and 1 means as row given in axis.

np.max(a1,axis=1)

array([98., 81., 85., 53.])

In [ ]:
np.min(a1,axis=0)

array([44., 14., 14., 36.])

In [ ]:
# mean/median/mode/statistics

np.mean(a1)

np.float64(59.0625)

In [ ]:
np.median(a1,axis=0)

array([63.5, 56.5, 65.5, 60. ])

In [ ]:
np.std(a1) # standard deviation

np.float64(25.657525090117325)

In [ ]:
# Dot product : order should be ccolumn of 1 = row of second

# 3 * 4 = 4 * 5 etc

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(20).reshape(4,5)

np.dot(a2,a3)



array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [ ]:
# log and exponents
np.exp(a1)

array([[1.28516001e+19, 1.20260428e+06, 1.50609731e+35, 3.63797095e+42],
       [1.37338298e+32, 2.03828107e+34, 2.75851345e+33, 1.50609731e+35],
       [8.22301271e+36, 4.09399696e+35, 2.83075330e+23, 8.65934004e+16],
       [1.04137594e+23, 5.83461743e+14, 1.20260428e+06, 4.31123155e+15]])

In [ ]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[72., 70., 82.],
       [61., 83., 31.]])

**Indexing and SLicing**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# Indexing

a1[-1] # Last element
a1[0]

np.int64(0)

In [ ]:
#2d iindexing  row and column
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a2[1,0]

np.int64(4)

In [ ]:
# 3d tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]  # for (first_mat/second_mat,row,column)

np.int64(5)

In [ ]:
a3[0,1,1]

np.int64(3)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
#Slicing: many elemennts to be taken out together

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
# 5 6 9 10

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [70]:
## Slicing for 3d array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [71]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [75]:
a1

for i in a1:
  print(a1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [76]:
a2

for i in a2:
  print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [77]:
a3

for i in a3:
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [79]:
# iterating in each value
# transformes the 3d or 2d into 1d.
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping**

In [80]:
#Transpose:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [81]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [82]:
# ravel : converts any dimension array in 1d array
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**Stacking** : Adding two or more arrays together


In [85]:
#horinzontal stacking: It adds two arrays sidewise.
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [86]:
np.hstack((a4,a5)) # can add as much as can

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [89]:
# Vertical stacking: Adds from top to bottom of two arryas.

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Spilitting**